# renovate: datasource=git-refs depName=tmux-plugins/tpm packageName=https://github.com/tmux-plugins/tpm versioning=git
["plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    revision = "e261deb1b47614eed3400089ce7197dc68acc4eb"
